# This is a basic workflow to help you get started with Actions

name: Linux 7.0.1 for MS-R1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: sudo apt install -y build-essential bc bison flex libelf-dev libssl-dev debhelper dh-exec rsync cpio kmod gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu libc6-dev-arm64-cross

      # Runs a set of commands using the runners shell
      - name: Download linux 7.0.1 source
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.0.1.tar.xz
          tar -xf linux-7.0.1.tar.xz

      - name: Apply Patches
        run: |
          cd linux-7.0.1
          echo "Patching kernel"
          patch -p1 < ../msr1-7.0.1.patch

      - name: Apply Config
        run: |
          cd linux-7.0.1
          echo "Applying config"
          cp ../config/config-msr1-7.0.1 .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

      - name: Build ARM64 Debian Packages
        run: |
          cd linux-7.0
          echo "Building kernel"
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) LOCALVERSION="-sky1-msr1" bindeb-pkg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-image-7.0.1-arm64-msr1-debs
          path: ./*.deb
